services:
  - type: web
    name: DNET
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd packages/ains-core/python && bash startup.sh
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
